### ISSUE TITLE
NameError: name 'fcntl' is not defined

### ISSUE THREAD

**Issue by chaoscreater** [kiwiz/keep-cli#10]
Does this work on Windows? I can login successfully, but then get the following errors:

![image](https://user-images.githubusercontent.com/18227319/229003593-081a077f-ede0-4200-bd8a-cfe532dc24ef.png)

https://stackoverflow.com/questions/54357073/nameerror-name-fcntl-is-not-defined-when-using-urwid-on-windows

**Comment by ooker777** [comment]
Here is the log I get when running `keep tui`:
```
Username: ganuongphap@gmail.com
[INFO] Authenticating with token
WARNING:root:Unable to find state file: C:\Users\ganuo/.keep\ganuongphap@gmail.com.json
[INFO] Success
INFO:keep-cli:Success
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ganuo\AppData\Local\Programs\Python\Python311\Scripts\keep.exe\__main__.py", line 7, in <module>
  File "C:\Users\ganuo\AppData\Local\Programs\Python\Python311\Lib\site-packages\keep_cli\__main__.py", line 190, in main
    args.func(args, keep, config)
  File "C:\Users\ganuo\AppData\Local\Programs\Python\Python311\Lib\site-packages\keep_cli\commands.py", line 44, in tui
    app.run()
  File "C:\Users\ganuo\AppData\Local\Programs\Python\Python311\Lib\site-packages\keep_cli\application.py", line 132, in run
    loop = urwid.MainLoop(self, constants.Palette)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ganuo\AppData\Local\Programs\Python\Python311\Lib\site-packages\urwid\main_loop.py", line 115, in __init__
    screen = raw_display.Screen()
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ganuo\AppData\Local\Programs\Python\Python311\Lib\site-packages\urwid\raw_display.py", line 92, in __init__
    fcntl.fcntl(self._resize_pipe_rd, fcntl.F_SETFL, os.O_NONBLOCK)
    ^^^^^
NameError: name 'fcntl' is not defined
```

Python 3.11.3 on Windows 11.

I then try using WSL and this is what I get: https://github.com/jaraco/keyring/issues/647
