### ISSUE TITLE
Import errors: python 3.10 in Windows

### ISSUE THREAD

**Issue by averyfreeman** [kiwiz/keep-cli#8]
```
C:\Windows\System32\drivers\etc>keep-cli --help
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\keep-cli.exe\__main__.py", line 4, in <module>
  File "C:\Python310\lib\site-packages\keep\keep.py", line 19, in <module>
    from PyInquirer import prompt
  File "C:\Python310\lib\site-packages\PyInquirer\__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "C:\Python310\lib\site-packages\prompt_toolkit\__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "C:\Python310\lib\site-packages\prompt_toolkit\interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "C:\Python310\lib\site-packages\prompt_toolkit\application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "C:\Python310\lib\site-packages\prompt_toolkit\key_binding\bindings\basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "C:\Python310\lib\site-packages\prompt_toolkit\renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "C:\Python310\lib\site-packages\prompt_toolkit\styles\__init__.py", line 8, in <module>
    from .from_dict import *
  File "C:\Python310\lib\site-packages\prompt_toolkit\styles\from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (C:\Python310\lib\collections\__init__.py)
```
Does this look like a lack of dependencies?

 I will try to find a container, seems like this happens a lot with things I install using `pip`.

**Comment by kiwiz** [comment]
That looks like an unrelated package. This project ~isn't currently published to PyPI, so the only way to get it is to download it from Github.~ is published to PyPi under `google-keep-cli`.
